name: longread_postprocessing
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - samtools
  - ucsc-bedtobigbed
  - seqkit  
  - pip:
    - snakemake
    - jupyter
    - notebook
    - pytest
    - cython
    - pyfaidx
    - -e .

